### ISSUE TITLE
Move TODO-s to issues

### ISSUE THREAD

**Issue by szepeviktor** [chainguard-dev/actions#297]
- [ ] boilerplate/action.yaml:  # TODO(mattmoor): Cut a release of `boilerplate-check` we can use instead.
- [ ] setup-kind/action.yaml:    required: true # TODO(mattmoor): Make this optional
- [ ] setup-melange/action.yaml:    # TODO: the bubblewrap package available from "apt install"
